config/routes.rb
LegalUtility::Application.routes.draw do

  get "capitalization_records/index"

  get "capitalization_records/show"

  get "capitalization_records/create"

  get "equity_plans/index"

  get "equity_plans/create"

  get "equity_plans/show"

  resources :people

  resources :users

  resources :after_signup_wizard

  resources :companies do

    resources :equity_records, only: [:show, :index, :create, :destroy]
    resources :capitalization_records, only: [:show, :index, :create, :destroy]
    resources :equity_plans, only: [:show, :index, :create, :destroy]
    resources :documents
    resources :status_updates
  end

  resources :sessions, only: [:new, :create, :destroy]

  match 'flashdoc/:id' => 'static_pages#sendfile'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
 #should be inlucded thorugh app helper
 # include ActionView::Helpers::NumberHelper

  def home

  end

  def about
  end

  def help
  end

  def initial_capitalization


  end

  def sendfile
    @document = Document.find_by_id(params[:id])
    if @document.present?

      if @document.company.nil? || !validateCompanyAccess(@document.company_id)
        redirect_to root_url
      else

        path = @document.document.path
        index = path.rindex(File.extname(path))
        path = path[0..index-1] + ".swf"
        send_file(path)
      end
    else
      redirect_to root_url
    end
  end

  def wizard
    if params[:step].nil?
      @step = "Step 1"
      @company = Company.new
    else
      if params["Commit"] == "Next"
        @step = Steps[Steps.index(params[:step])+1]
      else
        @step = Steps[Steps.index(params[:step])-1]
      end
    end
  end

  private

    Steps = ["Step 1", "Step 2", "Step 3"]



end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home_signedin.html.erb
        <% if current_user.person.nil? %>
            We've noticed you haven't configured the data for your company yet. <%= link_to "Would you like to use the wizard?", after_signup_wizard_path(:company_details) %>
        <% end %>
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
      </div>
      <div class="row-fluid">
        <div class="span4">
          <h2>Grant Stock Options or Other Equity</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div><!--/span-->
        <div class="span4">
          <h2>Model a Financing Round</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div><!--/span-->
        <div class="span4">
          <h2>Contract Work</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div><!--/span-->
      </div><!--/row-->
      <div class="row-fluid">
        <div class="span4">
          <h2>Hire a new Employee</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div><!--/span-->
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div><!--/span-->
        <div class="span4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div><!--/span-->
      </div>

app/views/static_pages/_initial_capitalization_row.html.erb
<tr>
  <td><%= person.firstname %></td>
  <td><%= radio_button_tag "balance_of_equity", person.id, @balanceID == person.id, :onclick => "capForm.submit()" %></td>
  <td><%= number_field_tag "#{person.id}_percent", @percentages[person.id].to_s, min: 0, max: 100, size: 50 %></td>
  <td><%= label_tag "numberShares", number_with_delimiter(@shares[person.id]) %></td>
  <td>100%</td>
  <td>100%</td>
</tr>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <% if userSignedIn? %>
      <%= render "home_signedin" %>
<% else %>
      <h1>
    LUtility
  </h1>

  <%= link_to "Sign up", signup_path, class: "btn btn-large btn-primary" %><br><br>
   <%= link_to "Already a User? Sign in now", signin_path, class: "btn btn-large btn-primary" %>
   <% end %>
          </div>

app/views/static_pages/wizard.html.erb
<h1>StaticPages#initial_capitalization</h1>
<p>Find me in app/views/static_pages/initial_capitalization.html.erb</p>
<%= form_tag "wizard", method: :get do %>
    <% case @step
        when "Step 1"
    %>
        <%= render "companies/form" %>
    <%  when "Step 2" %>
        Step 2

    <%  when "Step 3" %>
        Step 3

    <%  when "Step 4" %>
        Step 4
    <%  when "Step 6" %>
        End
    <% end %>
    <%= hidden_field_tag "step", @step %>
    <table>
        <tr>
            <td><%= submit_tag "Previous", class: "btn btn-small btn-primary" %></td>
            <td><%= submit_tag "Next", class: "btn btn-small btn-primary" %></td>
        </tr>
    </table>
<%end%>