config/routes.rb
LegalUtility::Application.routes.draw do

  get "capitalization_records/index"

  get "capitalization_records/show"

  get "capitalization_records/create"

  get "equity_plans/index"

  get "equity_plans/create"

  get "equity_plans/show"

  resources :people

  resources :users

  resources :after_signup_wizard

  resources :companies do

    resources :equity_records, only: [:show, :index, :create, :destroy]
    resources :capitalization_records, only: [:show, :index, :create, :destroy]
    resources :equity_plans, only: [:show, :index, :create, :destroy]
    resources :documents
    resources :status_updates
  end

  resources :sessions, only: [:new, :create, :destroy]

  match 'flashdoc/:id' => 'static_pages#sendfile'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

end

app/models/person.rb
class Person < ActiveRecord::Base
 attr_accessible :first_name, :last_name, :email, :middle_name, :street_address, :city_state_zip, :country, :phone

 has_many :relation_person_companies
 has_many :companies, through: :relation_person_companies
 has_many :equity_records

 validates :first_name, :last_name, :street_address, :city_state_zip, presence: true
 VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  def formatted_name
    if middle_name.present?
      middle = "#{middle_name[0]}. "
    else
      middle = " "
    end

    "#{first_name} #{middle}#{last_name}"
  end


 #TODO migrate this to a module to extend all saves with object logging
 def save_with_logging(user)
   jsonstring = valid? ? Person.find_by_id(id).to_json : nil
   save!   # do the original
   ChangeLog.create(objid: id, objtype: "Person", objjson: jsonstring, user_id: user.id).save! unless jsonstring.nil?
 end

  #def self.load_from_log(strUser)
  #  strUser
  #end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :middlename %><br />
    <%= f.text_field :middlename %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :entityname %><br />
    <%= f.text_field :entityname %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :streetaddress %><br />
    <%= f.text_field :streetaddress %>
  </div>
  <div class="field">
    <%= f.label :city_state_zip %><br />
    <%= f.text_field :city_state_zip %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Middlename</th>
    <th>Lastname</th>
    <th>Entityname</th>
    <th>Type</th>
    <th>Streetaddress</th>
    <th>City state zip</th>
    <th>Country</th>
    <th>Phone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.firstname %></td>
    <td><%= person.middlename %></td>
    <td><%= person.lastname %></td>
    <td><%= person.entityname %></td>
    <td><%= person.type %></td>
    <td><%= person.streetaddress %></td>
    <td><%= person.city_state_zip %></td>
    <td><%= person.country %></td>
    <td><%= person.phone %></td>
    <td><%= person.email %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @person.firstname %>
</p>

<p>
  <b>Middlename:</b>
  <%= @person.middlename %>
</p>

<p>
  <b>Lastname:</b>
  <%= @person.lastname %>
</p>

<p>
  <b>Entityname:</b>
  <%= @person.entityname %>
</p>

<p>
  <b>Type:</b>
  <%= @person.type %>
</p>

<p>
  <b>Streetaddress:</b>
  <%= @person.streetaddress %>
</p>

<p>
  <b>City state zip:</b>
  <%= @person.city_state_zip %>
</p>

<p>
  <b>Country:</b>
  <%= @person.country %>
</p>

<p>
  <b>Phone:</b>
  <%= @person.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @person.email %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>