config/routes.rb
LegalUtility::Application.routes.draw do

  get "capitalization_records/index"

  get "capitalization_records/show"

  get "capitalization_records/create"

  get "equity_plans/index"

  get "equity_plans/create"

  get "equity_plans/show"

  resources :people

  resources :users

  resources :after_signup_wizard

  resources :companies do

    resources :equity_records, only: [:show, :index, :create, :destroy]
    resources :capitalization_records, only: [:show, :index, :create, :destroy]
    resources :equity_plans, only: [:show, :index, :create, :destroy]
    resources :documents
    resources :status_updates
  end

  resources :sessions, only: [:new, :create, :destroy]

  match 'flashdoc/:id' => 'static_pages#sendfile'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :updateToken

  attr_accessible :password_digest, :email, :password_confirmation, :password

  has_secure_password

  belongs_to :person
  belongs_to :active_company, class_name: "Company", foreign_key: :active_company_id

  def self.authenticate(email, password)

      User.find_by_email(email).try(:authenticate, password)
  end

  # validates :presence, :email
  # validates :presence, :password_digest


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  def find_company_fuzzy( fuzzyname )

    matches = []

    #todo - Find Company Fuzzy needs serious work
    person.companies.each{|company| matches << company if company.name.downcase.include?(fuzzyname.downcase)}

    matches.length == 1 ? matches[0] : nil

  end




  private

  def updateToken()
    self.session_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end


  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    if @user.save
      signUserIn(@user)
      sign_in_redirect_helper root_path
    else
      render "new"
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<h2>Welcome. Create your profile: </h2>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :email %>
    <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirm" %>
      <%= f.password_field :password_confirmation %>
    <br>
    <%= f.submit %>
<% end %>
</div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th>Personid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.name %></td>
    <td><%= user.personid %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form' %>