config/routes.rb
LegalUtility::Application.routes.draw do

  get "capitalization_records/index"

  get "capitalization_records/show"

  get "capitalization_records/create"

  get "equity_plans/index"

  get "equity_plans/create"

  get "equity_plans/show"

  resources :people

  resources :users

  resources :after_signup_wizard

  resources :companies do

    resources :equity_records, only: [:show, :index, :create, :destroy]
    resources :capitalization_records, only: [:show, :index, :create, :destroy]
    resources :equity_plans, only: [:show, :index, :create, :destroy]
    resources :documents
    resources :status_updates
  end

  resources :sessions, only: [:new, :create, :destroy]

  match 'flashdoc/:id' => 'static_pages#sendfile'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root to: 'static_pages#home'

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :street_address, :city_state_zip, :phone, :fax, :business_description

  validates :name, presence: true
  validates :street_address, presence: true
  validates :city_state_zip, presence: true
  validates :phone, presence: true


  has_many :relation_person_companies

  has_many :status_updates

  has_many :documents

  #uniq collapses redundant records created by multiple relationships
  has_many :people, through: :relation_person_companies, uniq: true

  has_many :capitalization_records
  has_many :equity_records
  has_many :equity_plans

  def retrieve_document( docType)
      #documents.where("document_type = #{docType}")
      docs = documents.where(document_type: docType)
      return nil if docs.length == 0
      return docs[0]
  end

  def Charter
    retrieve_document (Constants::DOCUMENTTYPE_CHARTER)
  end

  def Bylaws

  end

  def Directors

  end

  def Officers

  end


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter { |cntr|  redirect_to root_path if !validateCompanyAccess(params[:id])}
  helper_method :resolve_document_link

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
    @status_updates = @company.status_updates


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  def resolve_document_link(company, displayText, documentType)
    document = company.retrieve_document(documentType)
    classAttr = ""
    if document.nil?
      displayText = "#{displayText} (missing)" if document.nil?
      url = new_company_document_path(company, document, docType: documentType)
      classAttr = "missing"
    else
      url = company_document_path(company, document)
    end
    "<i class='icon-file'></i><a href='#{url}' class='#{classAttr}'>#{displayText}</a>".html_safe
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper

  def validateCompanyAccess(companyID)
    if current_user.nil? || current_user.person.nil? || current_user.person.companies.nil?
      return false
    end

    arrCompanies = current_user.person.companies
    found = false
    arrCompanies.each do |c|
      if c.id == Integer(companyID)
         found = true
      end
    end

    if found && current_user.active_company_id != Integer(companyID)
      current_user.active_company_id = Integer(companyID)
      current_user.save!

      #saves trigger new keys, so update session
      updateSessionCookie
    end

    return found
  end


end

app/views/companies/_company_detail.html.erb
<div class="row-fluid">
  <div class="span12 shadow">
<h2><%= company.name %></h2>
<div style="margin-left: 15px">
  <%= resolve_document_link(company, "Certificate of Incorporation", Constants::DOCUMENTTYPE_CHARTER) %>

  <i class="icon-file"></i><a href="">Bylaws</a>
  <br><br>
  <div class="row-fluid">
    <div class="span6">
      Directors
      <ul class="unstyled">
        <li><i class="icon-user"></i><a href="">Jeff Laretto</a></li>
        <li><i class="icon-user"></i><a href="">Ben Carver</a></li>
      </ul>
    </div>
    <div class="span6">
      Officers
      <ul class="unstyled">
        <li><i class="icon-user"></i>President (<a href="">Jeff Laretto</a>)</li>
        <li><i class="icon-user"></i>Secretary (<a href="">Ben Carver</a>)</li>
      </ul>
    </div>
  </div>
  Critical Documents
  <ul class="unstyled">
    <li><i class="icon-file"></i><a href="">Investor Rights Agreement</a></li>
    <li><i class="icon-file"></i><a href="">Voting Agreement</a></li>
  </ul>

  Capitalization Snapshot
  <table class="table table-condensed">
    <thead>
    <tr>
      <th>Class</th>
      <th>Authorized</th>
      <th>Issued</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>Common</td>
      <td>10,000,000</td>
      <td>7,000,000</td>
    </tr>
    <tr>
      <td>Preferred</td>
      <td>2,000,000</td>
      <td>2,000,000</td>
    </tr>
    <tr>
      <td>2011 Equity Plan</td>
      <td>1,000,000</td>
      <td>500,000</td>
    </tr>
    </tbody>

  </table>
</div>
​</div>
</div>
<%= link_to "Add Document", new_company_document_path(@company) %>
<%= link_to "Show all Documents", company_documents_path(@company) %>

app/views/companies/_company_status_updates.html.erb
<div class="row-fluid">
  <div class="span12 shadow">
<% if @company.status_updates.any? %>
    <h3>Status Updates (<%= @company.status_updates.count %>)</h3>
    <ol class="status_updates">
      <%= render @status_updates %>
    </ol>
<% else %>
    <h3>No Updates Yet</h3>
<% end %>

</div>
    </div>

app/views/companies/_form.html.erb
<%= form_for(@company, url: wizard_path, method: :put) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <div class="row">
      <div class="span4">
      <%= f.label :name, "Corporate Name" %>
</div><div class="span8">
      <%= f.text_field :name %>
    </div></div>

    <div class="row">
      <div class="span4">
        &nbsp;
      </div><div class="span4">
      <span class="explanatory">Please enter the legal name of the entity you represent. The legal name requires a corporate designation appended at the end (e.g. Inc., Incorporated, Corp., Corporation or Limited.</span>
    </div></div>


<div class="row">
  <div class="span4">
    <%= f.label :streetaddress %>
  </div><div class="span8">
  <%= f.text_field :streetaddress %>
</div></div>

<div class="row">
  <div class="span4">
    <%= f.label :city_state_zip %>
  </div><div class="span8">
  <%= f.text_field :city_state_zip %>
</div></div>


    <div class="row">
      <div class="span4">
      <%= f.label :phone %>
      </div><div class="span8">
      <%= f.text_field :phone %>
    </div></div>

    <div class="row">
      <div class="span4">
      <%= f.label :fax, "Fax (Optional" %>
      </div><div class="span8">
      <%= f.text_field :fax %>
    </div></div>

    <div class="row">
      <div class="span4">
      <%= f.label :business_description, "Brief description of the business" %>
      </div><div class="span8">
      <%= f.text_area :business_description, rows: "5" %>
    </div></div>
  </div>

    <div class="row">
      <div class="span4">
      &nbsp;
      </div>
      <div class="span8">
        <%= f.submit "Next", class: "btn btn-large btn-primary" %>
      </div>
    </div>
<% end %>
>>
<%= debug wizard_path %><<

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Street address</th>
    <th>City state zip</th>
    <th>State of incorporation</th>
    <th>Phone</th>
    <th>Fax</th>
    <th>Business description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.street_address %></td>
    <td><%= company.city_state_zip %></td>
    <td><%= company.state_of_incorporation %></td>
    <td><%= company.phone %></td>
    <td><%= company.fax %></td>
    <td><%= company.business_description %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<div class="center-hero-unit">
  <div class="row-fluid">
    <div class="span7 bdr">
      <%= render partial: 'company_detail', locals: {company: @company}  %>

    </div>

    <div class="span5 bdr">
      <%= render 'company_status_updates' %>
      </div>
    </div>

  </div>
    <div class="row-fluid">
        <div class="span12 bdr">
            <%= render 'company_status_updates' %>
        </div>
    </div>
  </div>
</div>​